baseURL = 'https://koalacoaching.com/'
languageCode = 'en-us'
title = 'koalacoaching.com'

theme = 'ceres'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = ''
  tags = ''
